name: boredom
description: boredom
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  overlay_support: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2

  flutter_riverpod: ^2.4.0
  hive: ^2.2.3
  dio: ^5.3.3
  retry: ^3.1.2
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  objectbox: 2.2.0
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: any
  objectbox_generator: any

flutter:
  uses-material-design: true
